### ISSUE TITLE
Login/Register page does not work well with password manager

### ISSUE THREAD

**Issue by liemlyquan** [nhanb/pytaku#2]
The current login/register includes both functions, which make the password manager, e.g: 1Password, unable to 
- Save the correct fields credentials
- Autofill the fields quickly

I would suggest separating these two pages, instead of putting in one

**Comment by nhanb** [comment]
![Screenshot_20200809_084912](https://user-images.githubusercontent.com/1446315/89723191-497c2180-da1d-11ea-9df2-367695089ddc.png)
Lastpass on Firefox works fine, so this seems like a manager-specific problem. Will try playing with 1password... soon. Sometime.

**Comment by liemlyquan** [comment]
I think the problem is minor than I initially thought. The reason it does not autofill correctly is that the automatic process of saving credentials missed username information (1Password, Chrome)

<img width="309" alt="Screen Shot 2020-08-09 at 09 02 51" src="https://user-images.githubusercontent.com/5410411/89723352-38ccab00-da1f-11ea-8b42-fa0014257817.png">

Once I manually edit the entry in 1Password, works flawlessly

**Comment by nhanb** [comment]
haha cool
